teams:
  - name: lf-staff
    maintainers:
      - ryjones
    members:
      - SeanBohan
      - jwagantall
      - LF-Europe

  - name: security-managers
    maintainers:
      - jwagantall
      - ryjones

  - name: owners
    maintainers:
      - chamarat-wso2
      - git-repo-creation-app
      - maheshika
      - ryjones

  - name: core-maintainers
    maintainers:
      - maheshika
    members:
      - darshanasbg
      - isharak
      - omindu
      - senthalan

  - name: area-maintainers
    maintainers:
      - maheshika
    members:
      - AnuradhaSK
      - anushasunkada
      - ayshsandu
      - brionmario
      - rajithacharith
      - jeradrutnam
      - DonOmalVindula
      - KaveeshaPiumini
      - madurangasiriwardena
      - sahandilshan
      - ThaminduDilshan
      - thiva-k
      - ThumulaPerera

  - name: doc-maintainers
    maintainers:
      - maheshika
    members:
      - himeshsiriwardana
      - sagara-gunathunga

  - name: contributors
    maintainers:
      - maheshika
    members:
      - JayaShakthi97
      - Malith-19
      - NipuniBhagya
      - Thumimku
      - UdeshAthukorala
      - ayeshajay
      - hwupathum
      - indeewari
      - piraveena
      - NutharaNR
      - sadilchamishka
      - ImalshaD
      - ZiyamSanthosh
      - PasinduYeshan
      - shashimalcse

  - name: thunder-automation-bot
    maintainers:
      - maheshika
    members:
      - thunder-automation-bot

  - name: wso2-digital-statistics-bot
    maintainers:
      - maheshika
    members:
      - wso2-digital-statistics-bot

repositories:
  - name: governance
    teams:
      lf-staff: admin
    visibility: public
  - name: .github
    teams:
      owners: admin
      core-maintainers: write
      area-maintainers: write
      doc-maintainers: write
    visibility: public
  - name: android-sdks
    teams:
      owners: admin
      core-maintainers: write
      area-maintainers: write
      doc-maintainers: write
      contributors: triage
      thunder-automation-bot: admin
    visibility: public
  - name: flutter-sdks
    teams:
      owners: admin
      core-maintainers: write
      area-maintainers: write
      doc-maintainers: write
      contributors: triage
      thunder-automation-bot: admin
    visibility: public
  - name: ios-sdks
    teams:
      owners: admin
      core-maintainers: write
      area-maintainers: write
      doc-maintainers: write
      contributors: triage
      thunder-automation-bot: admin
    visibility: public
  - name: javascript-sdks
    teams:
      owners: admin
      core-maintainers: write
      area-maintainers: write
      doc-maintainers: write
      contributors: triage
      thunder-automation-bot: admin
    visibility: public
  - name: skills
    teams:
      owners: admin
      core-maintainers: write
      area-maintainers: write
      doc-maintainers: write
      contributors: triage
      thunder-automation-bot: admin
    visibility: public
  - name: thunderid
    teams:
      owners: admin
      core-maintainers: write
      area-maintainers: write
      doc-maintainers: write
      contributors: triage
      thunder-automation-bot: admin
      wso2-digital-statistics-bot: write
    visibility: public
