teams:
  - name: area-committers
    maintainers:
      - maheshika
    members:
      - AnuradhaSK
      - anushasunkada
      - ayshsandu
      - brionmario
      - DonOmalVindula
      - jeradrutnam
      - KaveeshaPiumini
      - madurangasiriwardena
      - rajithacharith
      - sahandilshan
      - ThaminduDilshan
      - thiva-k
      - ThumulaPerera

  - name: contributors
    maintainers:
      - maheshika
    members:
      - ayeshajay
      - hwupathum
      - ImalshaD
      - indeewari
      - JayaShakthi97
      - Malith-19
      - NipuniBhagya
      - NutharaNR
      - PasinduYeshan
      - piraveena
      - sadilchamishka
      - shashimalcse
      - Thumimku
      - UdeshAthukorala
      - ZiyamSanthosh

  - name: core-maintainers
    maintainers:
      - maheshika
    members:
      - darshanasbg
      - isharak
      - omindu
      - senthalan

  - name: doc-committers
    maintainers:
      - maheshika
    members:
      - himeshsiriwardana
      - sagara-gunathunga

  - name: lf-staff
    maintainers:
      - ryjones
    members:
      - jwagantall
      - LF-Europe
      - SeanBohan

  - name: owners
    maintainers:
      - chamarat-wso2
      - git-repo-creation-app
      - maheshika
      - ryjones

  - name: security-managers
    maintainers:
      - darshanasbg
      - isharak
      - jwagantall
      - omindu
      - ryjones
      - senthalan

  - name: thunder-automation-bot
    maintainers:
      - maheshika
    members:
      - thunder-automation-bot

  - name: wso2-digital-statistics-bot
    maintainers:
      - maheshika
    members:
      - wso2-digital-statistics-bot

repositories:
  - name: .github
    teams:
      area-committers: write
      core-maintainers: maintain
      doc-committers: write
      owners: admin
    visibility: public
  - name: android-sdks
    teams:
      area-committers: write
      contributors: triage
      core-maintainers: maintain
      doc-committers: write
      owners: admin
      thunder-automation-bot: admin
    visibility: public
  - name: flutter-sdks
    teams:
      area-committers: write
      contributors: triage
      core-maintainers: maintain
      doc-committers: write
      owners: admin
      thunder-automation-bot: admin
    visibility: public
  - name: governance
    teams:
      core-maintainers: maintain
      lf-staff: admin
    visibility: public
  - name: ios-sdks
    teams:
      area-committers: write
      contributors: triage
      core-maintainers: maintain
      doc-committers: write
      owners: admin
      thunder-automation-bot: admin
    visibility: public
  - name: javascript-sdks
    teams:
      area-committers: write
      contributors: triage
      core-maintainers: maintain
      doc-committers: write
      owners: admin
      thunder-automation-bot: admin
    visibility: public
  - name: skills
    teams:
      area-committers: write
      contributors: triage
      core-maintainers: maintain
      doc-committers: write
      owners: admin
      thunder-automation-bot: admin
    visibility: public
  - name: thunderid
    teams:
      area-committers: write
      contributors: triage
      core-maintainers: maintain
      doc-committers: write
      owners: admin
      thunder-automation-bot: admin
      wso2-digital-statistics-bot: write
    visibility: public
